### PR TITLE
add `npm start` and add link to invite bot

### LINKED ISSUE #2: please add bot install instructions
it would be handy to have a premade url with all the scopes, etc necessary to get the bot in. it would be double excellent if you had a "deploy to heroku" button (it appears you're missing an app.json file)

thanks!

### PR DESCRIPTION
**Pull request by seiyria**
Fixes #2

### CODE REVIEW

**Comment by navn-r** [comment]
Thanks @seiyria, I'll take a look later and get this in for you.  Please let me know when this PR is ready to go. It would be great to add the `App.json` to this PR.

**Comment by seiyria** [comment]
unfortunately I don't know enough about heroku to do that confidently

**Comment by navn-r** [comment]
No worries, I'll make an issue regarding the App.json.

**Review by navn-r — APPROVED** [review]
LGTM!

**Pull request merged**
